// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCp9CgpBY3RvclN0YXRlEhQKEEFDVE9S",
            "X1NUQVRFX05PTkUQABIUChBBQ1RPUl9TVEFURV9JRExFEAESFgoSQUNUT1Jf",
            "U1RBVEVfTU9WSU5HEAISFQoRQUNUT1JfU1RBVEVfU0tJTEwQAxIUChBBQ1RP",
            "Ul9TVEFURV9ERUFEEAQqhgEKCUFjdG9yVHlwZRITCg9BQ1RPUl9UWVBFX05P",
            "TkUQABIVChFBQ1RPUl9UWVBFX1BMQVlFUhABEhYKEkFDVE9SX1RZUEVfTU9O",
            "U1RFUhACEhkKFUFDVE9SX1RZUEVfUFJPSkVDVElMRRADEhoKFkFDVE9SX1RZ",
            "UEVfSVRFTV9IT0xERVIQBCpOChFUaWxlQ29sbGlzaW9uVHlwZRIcChhUSUxF",
            "X0NPTExJU0lPTl9UWVBFX05PTkUQABIbChdUSUxFX0NPTExJU0lPTl9UWVBF",
            "X0VOVhABKtwBCg5GaW5kUGF0aFJlc3VsdBIZChVGSU5EX1BBVEhfUkVTVUxU",
            "X05PTkUQABIiCh5GSU5EX1BBVEhfUkVTVUxUX0ZBSUxfTEVSUENFTEwQARIh",
            "Ch1GSU5EX1BBVEhfUkVTVUxUX0ZBSUxfTk9fUEFUSBACEiEKHUZJTkRfUEFU",
            "SF9SRVNVTFRfRkFJTF9NT1ZFX1RPEAMSJwojRklORF9QQVRIX1JFU1VMVF9G",
            "QUlMX1NBTUVfUE9TSVRJT04QBBIcChhGSU5EX1BBVEhfUkVTVUxUX1NVQ0NF",
            "U1MQBSrFAQoHTW92ZURpchIRCg1NT1ZFX0RJUl9OT05FEAASDwoLTU9WRV9E",
            "SVJfVVAQARIRCg1NT1ZFX0RJUl9ET1dOEAISEQoNTU9WRV9ESVJfTEVGVBAD",
            "EhIKDk1PVkVfRElSX1JJR0hUEAQSFAoQTU9WRV9ESVJfVVBfTEVGVBAFEhUK",
            "EU1PVkVfRElSX1VQX1JJR0hUEAYSFgoSTU9WRV9ESVJfRE9XTl9MRUZUEAcS",
            "FwoTTU9WRV9ESVJfRE9XTl9SSUdIVBAIKkwKClNlcnZlclR5cGUSGwoXU0VS",
            "VkVSX1RZUEVfR0FNRV9TRVJWRVIQABIhCh1TRVJWRVJfVFlQRV9NT05JVE9S",
            "SU5HX1NFUlZFUhABYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.ActorState), typeof(global::Protocol.ActorType), typeof(global::Protocol.TileCollisionType), typeof(global::Protocol.FindPathResult), typeof(global::Protocol.MoveDir), typeof(global::Protocol.ServerType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ActorState {
    [pbr::OriginalName("ACTOR_STATE_NONE")] None = 0,
    [pbr::OriginalName("ACTOR_STATE_IDLE")] Idle = 1,
    [pbr::OriginalName("ACTOR_STATE_MOVING")] Moving = 2,
    [pbr::OriginalName("ACTOR_STATE_SKILL")] Skill = 3,
    [pbr::OriginalName("ACTOR_STATE_DEAD")] Dead = 4,
  }

  public enum ActorType {
    [pbr::OriginalName("ACTOR_TYPE_NONE")] None = 0,
    [pbr::OriginalName("ACTOR_TYPE_PLAYER")] Player = 1,
    [pbr::OriginalName("ACTOR_TYPE_MONSTER")] Monster = 2,
    [pbr::OriginalName("ACTOR_TYPE_PROJECTILE")] Projectile = 3,
    [pbr::OriginalName("ACTOR_TYPE_ITEM_HOLDER")] ItemHolder = 4,
  }

  public enum TileCollisionType {
    [pbr::OriginalName("TILE_COLLISION_TYPE_NONE")] None = 0,
    [pbr::OriginalName("TILE_COLLISION_TYPE_ENV")] Env = 1,
  }

  public enum FindPathResult {
    [pbr::OriginalName("FIND_PATH_RESULT_NONE")] None = 0,
    [pbr::OriginalName("FIND_PATH_RESULT_FAIL_LERPCELL")] FailLerpcell = 1,
    [pbr::OriginalName("FIND_PATH_RESULT_FAIL_NO_PATH")] FailNoPath = 2,
    [pbr::OriginalName("FIND_PATH_RESULT_FAIL_MOVE_TO")] FailMoveTo = 3,
    [pbr::OriginalName("FIND_PATH_RESULT_FAIL_SAME_POSITION")] FailSamePosition = 4,
    [pbr::OriginalName("FIND_PATH_RESULT_SUCCESS")] Success = 5,
  }

  public enum MoveDir {
    [pbr::OriginalName("MOVE_DIR_NONE")] None = 0,
    [pbr::OriginalName("MOVE_DIR_UP")] Up = 1,
    [pbr::OriginalName("MOVE_DIR_DOWN")] Down = 2,
    [pbr::OriginalName("MOVE_DIR_LEFT")] Left = 3,
    [pbr::OriginalName("MOVE_DIR_RIGHT")] Right = 4,
    [pbr::OriginalName("MOVE_DIR_UP_LEFT")] UpLeft = 5,
    [pbr::OriginalName("MOVE_DIR_UP_RIGHT")] UpRight = 6,
    [pbr::OriginalName("MOVE_DIR_DOWN_LEFT")] DownLeft = 7,
    [pbr::OriginalName("MOVE_DIR_DOWN_RIGHT")] DownRight = 8,
  }

  public enum ServerType {
    [pbr::OriginalName("SERVER_TYPE_GAME_SERVER")] GameServer = 0,
    [pbr::OriginalName("SERVER_TYPE_MONITORING_SERVER")] MonitoringServer = 1,
  }

  #endregion

}

#endregion Designer generated code
